platform:ios,'8.0'

pod 'Masonry'
pod 'AFNetworking'
pod 'BaiduMapAPI', '~> 2.8.1'
pod 'SDWebImage', '~>3.7'
pod 'IQKeyboardManager'
pod 'ChameleonFramework'
pod 'SSKeychain'
pod 'Mantle', '~> 2.0.5'
pod "Qiniu", "~> 7.0"
pod 'SDCycleScrollView','~> 1.3'
pod 'NJKWebViewProgress'
pod 'JPush', '~> 1.8.7'
pod 'MJRefresh'
pod 'UMengAnalytics-NO-IDFA'
pod 'RESideMenu', '~> 4.0.7'
